# Generated by Django 6.0.6 on 2026-07-08 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('commerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.productplanmodel'),
        ),
        migrations.AddField(
            model_name='cartitemmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.productmodel'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='commerce.couponmodel'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitemmodel',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.cartmodel'),
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.productplanmodel'),
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commerce.productmodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.couponmodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.ordermodel'),
        ),
        migrations.AddConstraint(
            model_name='cartitemmodel',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'plan'), name='unique_cart_product_plan'),
        ),
    ]
