# Generated by Django 6.0.6 on 2026-07-08 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.couponmodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='subtotal',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
