# Generated by Django 6.0.6 on 2026-07-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_ordermodel_coupon_ordermodel_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitemmodel',
            name='service_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
