# Generated by Django 6.0.6 on 2026-07-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_cartitemmodel_is_renewal_cartitemmodel_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='is_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='service_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
