# Generated by Django 6.0.6 on 2026-07-01 17:17

import django.core.validators
import django.db.models.deletion
import finance.models.deposit
import finance.models.refund_to_user
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallets',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField()),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('purchase', 'Purchase'), ('refund_to_wallet', 'Refund To Wallet'), ('refund_to_user', 'Refund To User'), ('withdraw', 'Withdraw'), ('adjustment', 'Adjustment')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.walletmodel')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundToWalletRequestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField()),
                ('reason', models.TextField(help_text='Reason for issuing the refund.')),
                ('admin_note', models.TextField(blank=True, help_text='Internal note.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_refund_request', to='finance.transactionmodel')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_refund_requests', to='finance.walletmodel')),
            ],
            options={
                'verbose_name': 'Wallet Refund Request',
                'verbose_name_plural': 'Wallet Refund Requests',
                'db_table': 'wallet_refund_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundToUserRequestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField()),
                ('payment_method', models.CharField(choices=[('card_to_card', 'Card To Card'), ('online_gateway', 'Online Gateway')], default='card_to_card', max_length=30)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_card_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Invalid card number.', regex='^\\d{16}$')])),
                ('receiver_iban', models.CharField(blank=True, help_text='Optional IBAN (Sheba).', max_length=26)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_time', models.TimeField(blank=True, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to=finance.models.refund_to_user.receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('reason', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_refund_request', to='finance.transactionmodel')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_refund_requests', to='finance.walletmodel')),
            ],
            options={
                'verbose_name': 'User Refund Request',
                'verbose_name_plural': 'User Refund Requests',
                'db_table': 'user_refund_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request', to='finance.transactionmodel')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='finance.walletmodel')),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
                'db_table': 'purchase_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('purchase', 'Purchase'), ('refund_to_wallet', 'Refund To Wallet'), ('refund_to_user', 'Refund To User'), ('withdraw', 'Withdraw'), ('adjustment', 'Adjustment')], max_length=30)),
                ('amount', models.BigIntegerField()),
                ('balance_before', models.BigIntegerField()),
                ('balance_after', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entry', to='finance.transactionmodel')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.walletmodel')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'db_table': 'ledger_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositRequestModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField()),
                ('payment_method', models.CharField(choices=[('card_to_card', 'Card To Card'), ('online_gateway', 'Online Gateway')], default='card_to_card', max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_card_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Invalid card number.', regex='^\\d{16}$')])),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_time', models.TimeField(blank=True, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to=finance.models.deposit.receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_request', to='finance.transactionmodel')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_requests', to='finance.walletmodel')),
            ],
            options={
                'verbose_name': 'Deposit Request',
                'verbose_name_plural': 'Deposit Requests',
                'db_table': 'deposit_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
