# Generated by Django 6.0.6 on 2026-07-05 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='shop.ordermodel'),
        ),
        migrations.AddField(
            model_name='refundtowalletrequestmodel',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_refund_request', to='finance.transactionmodel'),
        ),
        migrations.AddField(
            model_name='refundtouserrequestmodel',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_refund_request', to='finance.transactionmodel'),
        ),
        migrations.AddField(
            model_name='purchaserequestmodel',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request', to='finance.transactionmodel'),
        ),
        migrations.AddField(
            model_name='ledgerentrymodel',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entry', to='finance.transactionmodel'),
        ),
        migrations.AddField(
            model_name='depositrequestmodel',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_request', to='finance.transactionmodel'),
        ),
        migrations.AddField(
            model_name='walletmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.walletmodel'),
        ),
        migrations.AddField(
            model_name='refundtowalletrequestmodel',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_refund_requests', to='finance.walletmodel'),
        ),
        migrations.AddField(
            model_name='refundtouserrequestmodel',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_refund_requests', to='finance.walletmodel'),
        ),
        migrations.AddField(
            model_name='purchaserequestmodel',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='finance.walletmodel'),
        ),
        migrations.AddField(
            model_name='ledgerentrymodel',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.walletmodel'),
        ),
        migrations.AddField(
            model_name='depositrequestmodel',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_requests', to='finance.walletmodel'),
        ),
    ]
