# Generated by Django 6.0.6 on 2026-07-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cardmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
