# Generated by Django 6.0.6 on 2026-07-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_cardmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundtouserrequestmodel',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refundtouserrequestmodel',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
