# Generated by Django 6.0.6 on 2026-07-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_refundtouserrequestmodel_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestmodel',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for issuing the purchase.', null=True),
        ),
        migrations.AlterField(
            model_name='depositrequestmodel',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Internal note.', null=True),
        ),
        migrations.AlterField(
            model_name='depositrequestmodel',
            name='note',
            field=models.TextField(blank=True, help_text='User note.', null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestmodel',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Internal note.', null=True),
        ),
        migrations.AlterField(
            model_name='refundtouserrequestmodel',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Internal note.', null=True),
        ),
        migrations.AlterField(
            model_name='refundtouserrequestmodel',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for issuing the refund.', null=True),
        ),
        migrations.AlterField(
            model_name='refundtowalletrequestmodel',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Internal note.', null=True),
        ),
        migrations.AlterField(
            model_name='refundtowalletrequestmodel',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for issuing the refund.', null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description.', null=True),
        ),
    ]
