# Generated by Django 6.0.6 on 2026-07-05 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean')], max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'db_table': 'features',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('vpn', 'VPN'), ('game', 'Game'), ('gift_card', 'Gift Card'), ('other', 'Other')], default='vpn', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique coupon code entered by the user (e.g. SAVE20).', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Internal title for admin display (not shown to customers).', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description explaining coupon rules or campaign details.')),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed Amount')], default='percent', help_text='Type of discount: percentage-based or fixed amount.', max_length=20)),
                ('discount_value', models.PositiveIntegerField(help_text="Discount value. If percentage, this is 0–100. If fixed, it's the amount in smallest currency unit.")),
                ('max_discount', models.PositiveIntegerField(blank=True, help_text='Maximum discount cap (only applies for percentage-based discounts).', null=True)),
                ('minimum_order_amount', models.PositiveBigIntegerField(default=1, help_text='Minimum order subtotal required to apply this coupon.')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used globally. Null = unlimited.', null=True)),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Total number of times this coupon has been used (should be synced with usage records).')),
                ('per_user_limit', models.PositiveIntegerField(default=1, help_text='Maximum number of times a single user can use this coupon.')),
                ('starts_at', models.DateTimeField(help_text='Datetime when the coupon becomes active.')),
                ('expires_at', models.DateTimeField(help_text='Datetime when the coupon expires and becomes invalid.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this coupon is active and can be used.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the coupon was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the coupon was last updated.')),
                ('allowed_products', models.ManyToManyField(blank=True, help_text='Restrict coupon to specific products. If empty, applies to all products.', to='commerce.productmodel')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPlanModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveBigIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='commerce.productmodel')),
            ],
            options={
                'verbose_name': 'Product Plan',
                'verbose_name_plural': 'Product Plans',
                'db_table': 'product_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeatureModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.featuremodel')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='commerce.productplanmodel')),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
                'db_table': 'plan_features',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='V2rayVPNModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_link', models.URLField()),
                ('content', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.orderitemmodel')),
            ],
            options={
                'verbose_name': 'VPN Provisioned Service',
                'verbose_name_plural': 'VPN Provisioned Services',
                'db_table': 'vpn_provisioned_services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.PositiveBigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='commerce.couponmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_usages', to='billing.ordermodel')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_usages', to='finance.walletmodel')),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'db_table': 'coupon_usages',
                'ordering': ['-created_at'],
                'unique_together': {('coupon', 'wallet', 'order')},
            },
        ),
    ]
