# Generated by Django 6.0.6 on 2026-07-08 22:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="IP address of the user's device.", null=True)),
                ('user_agent', models.TextField(blank=True, help_text="User agent of the user's device.", null=True)),
                ('device', models.CharField(blank=True, help_text="Device type of the user's device.", max_length=255, null=True)),
                ('browser', models.CharField(blank=True, help_text="Browser of the user's device.", max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, help_text="Operating system of the user's device.", max_length=100, null=True)),
                ('country', models.CharField(blank=True, help_text="Country of the user's device.", max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text="City of the user's device.", max_length=100, null=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('failure_reason', models.TextField(blank=True, help_text="Failure reason of the user's device.", null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'db_table': 'login_histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Target email for OTP delivery.', max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('otp_type', models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('verify_email', 'Verify email'), ('reset_password', 'Reset password')], default='login', help_text='Purpose of the OTP (login, register, etc.).', max_length=61)),
                ('salt', models.CharField(max_length=255)),
                ('code_hash', models.CharField(max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='authenticat_email_7d7235_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_used', False)), fields=('email', 'otp_type', 'is_used'), name='unique_active_otp_per_email_type')],
            },
        ),
    ]
