# Generated by Django 6.0.6 on 2026-07-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_couponmodel_couponusagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponmodel',
            name='allowed_products',
            field=models.ManyToManyField(blank=True, to='shop.productmodel'),
        ),
    ]
